[package]
name = "water"
version = "0.1.0"
edition = "2024"

[dependencies]
oogaxi = { path = "../.."}
bevy.workspace = true
bevy-inspector-egui = { version = "0.37"}
rand.workspace = true

# light optimization, fast recompiles
[profile.dev]
opt-level = 1

# dependencies: full optimisation, compile once
[profile.dev.package."*"]
opt-level = 3
